### ISSUE TITLE
FRITZ!OS BETA-Versions

### ISSUE THREAD

**Issue by Bejobe** [n0rc/fritzbox#11]
In combination with FritzOS 7.25 the changed script works fine. Thank you.

But I have here two boxes with FritzOS BETA-Versions (Fritz!BOX 7490 with 07.24-86493 BETA  and Fritz!BOX 7520 with 07.24-86863 BETA ). They both works like the FritzOS 7.25. 

But it is not enough to change the line in the script wakeup.py from 
   if version.parse(vers) < version.parse('7.25'):
into
  if version.parse(vers) < version.parse('7.24'):
because of the apendix -nnnnn BETA.

It is necessery to cut this appendix away by adding a new line:
   vers_nr = vers.split('-');
   if version.parse(vers_nr[0]) < version.parse('7.24'):

This is not only important for beta versions with 7.24 but also in the future for beta version higher than 7.25 (all versions with appendix, which is used often by AVM).

Best regards 

Bejobe

PS.: If you want I can open a Pull request for that.

**Comment by n0rc** [comment]
Fixed in a28e94cbb0fa05a81e79c9840bd7a2a7d2b0733d.
