### ISSUE TITLE
international 6.52 takes wrong password

### ISSUE THREAD

**Issue by tmpt1** [n0rc/fritzbox#3]
The international version with fritzos 6.52 fails to login. 
It seems that it takes the wrong password (the local password). 
This test seems to fail:  
my $pass = ($c =~ m#Benutzername#) ? $remote_pass : $local_admin_pass;
Maybe because the German term Benutzername? 
I changed this line to         my $pass = $remote_pass; 
and it works for my 6.52, but maybe it's not compatible anymore with other fritzos versions.

**Comment by n0rc** [comment]
Yes, that's very likely to be the cause of the problem. I'm shortly going to push a rewrite that simplifies the whole login process. This should also fix this bug.
