### ISSUE TITLE
Since fritzOS 6.83: [error] could not find a challenge

### ISSUE THREAD

**Issue by modr** [n0rc/fritzbox#4]
Hi,

since the Fritz.box updated to OS version 6.83 I always get the error message: 

[error] could not find a challenge

Could you pls check if the script needs amending?! 

Thanks a lot in advance.

**Comment by n0rc** [comment]
I don't have v6.83 available for testing right now but I pushed a new Python rewrite of the script that uses the API recommended by AVM. Please try if it works for you.

**Comment by n0rc** [comment]
I tested with v6.83 and it works with the Python version. Please reopen if it doesn't work for you.

**Comment by modr** [comment]
Thanks, works great from my local machine, but unfortunately ISP dies not support all required Python modules I lack the rights to install all required modules. Need to see how to fix or fix the Perl version.

**Comment by n0rc** [comment]
@modr Maybe take a look at https://stackoverflow.com/questions/7465445/ for instructions on how to install packages without root privileges.
