### ISSUE TITLE
Incompatibility with FritzOS 7.25

### ISSUE THREAD

**Issue by onliner2021** [n0rc/fritzbox#9]
In combination with FritzOS 7.25 the script does not work any more.
„[error] something went wrong while sending wakeup to …“.
I tried using the -k switch (without it I would additionally get "[error] ssl certificate verification failed)".
It looks like AVM managed to break the functionallity yet again.
Using Fritz!BOX 7590 hardware.

Thanks in advance.

**Comment by n0rc** [comment]
My Fritzbox has not received 7.25 yet, so I will have to wait to fix this.

It would be helpful if someone could post the response data after the [wakeup POST request](https://github.com/n0rc/fritzbox/blob/master/wakeup.py#L79).

**Comment by onliner2021** [comment]
If I do a print(r.content); after the line you highlighted, it returns the overview that contains the entire configuration of my FritzBox:
b'{"pid":"overview","hide":{"shareUsb":true,"liveTv":true,"dectRdio":true,"rss":true,"ssoSet":true,"dectMail":true,"provServ":true,"mobile":true,"liveImg":true},"time":[],"data":{"naslink":"usbOv","fritzos":{"Productname":"FRITZ!Box 7590","NoPwd":false,"ShowDefaults":false,"expert_mode":"1","fb_name":"","nspver":"07.25","isLabor":false,

...and so on. I cannot post the entire config here as that would expose my entire network MACs, machine names, telephone configuration and so on. But I am pretty sure, that the overview is not was expected after sending the command.
There is also no mention of btn_wake in the entire post content text.

**Comment by tmpt1** [comment]
I had the same problem. See my pull request that seems to work at my updated fritzbox.

**Comment by n0rc** [comment]
@tmpt1 Thanks! I still need to write some version handling to keep compatibility because this change breaks wakeups for previous versions of FritzOS.

@onliner2021 Could you please check out [this patch](https://github.com/n0rc/fritzbox/pull/10/commits/25210f0731a8afcfb9db93ea8e8d1c904d480d76) to see if this is working for you with 7.25?

**Comment by tmpt1** [comment]
> 
> 
> @tmpt1 Thanks! I still need to write some version handling to keep compatibility because this change breaks wakeups for previous versions of FritzOS.
> 

Sure, you're right. 
I updated the pull request. 
Had some difficulties reading out the json with fritzos information, but now i've got it working. 
At least...at fritzos 7.25 it seems to work. 
Couldn't test on older version, because I don't have that available anymore.

**Comment by onliner2021** [comment]
@tmpt1 Thanks! That works again with 7.25.
Great stuff.

**Comment by n0rc** [comment]
Please test the latest version of the script. It contains the version check and modified payload for FritzOS 7.25.

**Comment by tmpt1** [comment]
Great work. You're a better python progammer than I am. 
It works for me with the newest (7.25) fritzos. 
I only had to install new dependency for python packages

**Comment by n0rc** [comment]
Thanks for contributing and testing!
